---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

version: 1

name: simplyos
description: "SimplyOS"

base-image: ghcr.io/wayblueorg/sway
image-version: 44

modules:
  # Instalar paquetes
  - type: dnf
    install:
      packages:
        # Herramientas de compilación
        - git
        - gcc
        - meson
        - ninja-build
        - pkgconf-pkg-config

        # Dependencias de Cagebreak
        - wlroots-devel
        - pango-devel
        - wayland-devel
        - wayland-protocols-devel
        - libxkbcommon-devel
        - libseat-devel
        - libinput-devel
        - libliftoff-devel
        - libdrm-devel
        - mesa-libgbm-devel
        - libglvnd-devel
        - pixman-devel
        - libxcb-devel
        - xcb-util-errors-devel
        - xcb-util-renderutil-devel
        - xcb-util-wm-devel
        - xorg-x11-server-Xwayland

        # Aplicaciones
        - foot
        - fuzzel
        - waybar
        - mako
        - swaybg
        - fastfetch

        # Seguridad
        - firewalld
        - aide
        - fail2ban
        - lynis

  # Compilar Cagebreak
  - type: script
    scripts:
      - build-cagebreak.sh

  # Eliminar dependencias de compilación
  - type: dnf
    remove:
      packages:
        - git
        - gcc
        - meson
        - ninja-build
        - pkgconf-pkg-config
        - wayland-devel
        - wayland-protocols-devel
        - libxkbcommon-devel
        - libseat-devel
        - libinput-devel
        - libliftoff-devel
        - libdrm-devel
        - mesa-libgbm-devel
        - libglvnd-devel
        - pixman-devel
        - libxcb-devel
        - xcb-util-errors-devel
        - xcb-util-renderutil-devel
        - xcb-util-wm-devel
        - wlroots-devel
        - pango-devel
